# Generated by Django 4.1.2 on 2022-10-10 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_GASRF', models.CharField(max_length=50, null=True)),
                ('site', models.URLField(null=True)),
                ('region', models.CharField(max_length=250, null=True, verbose_name='Регион')),
                ('district', models.CharField(max_length=250, null=True, verbose_name='Район')),
                ('name_judicial_precinct', models.CharField(max_length=250, null=True, verbose_name='Наименование судебного участка')),
                ('address', models.CharField(max_length=250, null=True)),
                ('judge_full_name', models.CharField(max_length=250, null=True, verbose_name='ФИО Судьи')),
                ('judge_email', models.EmailField(max_length=254, null=True)),
                ('assistant_full_name', models.CharField(max_length=250, null=True, verbose_name='ФИО Помощника Судьи')),
                ('clerk_full_name', models.CharField(max_length=250, null=True, verbose_name='ФИО Секретаря судебного участка')),
                ('secretary_court_session', models.CharField(max_length=250, null=True, verbose_name='Секретаря судебного заседания')),
                ('type_phone_1', models.CharField(max_length=25, null=True)),
                ('phone_1', models.CharField(max_length=25, null=True)),
                ('type_phone_2', models.CharField(max_length=25, null=True)),
                ('phone_2', models.CharField(max_length=25, null=True)),
                ('type_phone_3', models.CharField(max_length=25, null=True)),
                ('phone_3', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=250, null=True, verbose_name='Район, населенный пункт')),
                ('street', models.CharField(max_length=250, null=True, verbose_name='микрорайон, улица, прочие адресные указатели')),
                ('house_number', models.CharField(max_length=6, null=True, verbose_name='номер дома, если в подсудность входят единичные дома')),
                ('start_house_number', models.CharField(max_length=6, null=True, verbose_name='номер дома начала интервала')),
                ('end_house_number', models.CharField(max_length=6, null=True, verbose_name='номер дома конца интервала')),
                ('parity', models.CharField(max_length=2, null=True)),
                ('excluded_houses', models.CharField(max_length=250, null=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurisdictions', to='courts.court')),
            ],
        ),
    ]
