# Generated by Django 4.1.2 on 2022-10-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0003_alter_jurisdiction_end_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurisdiction',
            name='end_house_number',
            field=models.CharField(max_length=6, null=True, verbose_name='номер дома конца интервала'),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='house_number',
            field=models.CharField(max_length=6, null=True, verbose_name='номер дома, если в подсудность входят единичные дома'),
        ),
        migrations.AlterField(
            model_name='jurisdiction',
            name='start_house_number',
            field=models.CharField(max_length=6, null=True, verbose_name='номер дома начала интервала'),
        ),
    ]
